language: java
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: echo "skip './gradlew assemble' step"
script: ./gradlew build --continue --no-daemon && mv -f build/libs/Primitives-proguard.jar build/libs/Primitives.jar 
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - "build/libs/Primitives.jar"
    - "build/libs/Primitives-javadoc.jar"
    - "build/libs/Primitives-sources.jar"
  skip_cleanup: true
  on:
    tags: true